
credentials:
    twitter_credentials: "credentials/twitter_credentials.json"
    google_drive_credentials: null
    is_twitter_elevated_access: false
storage:
    gdrive_folder_id: null
    dump_to_google_drive: false
    local_folder: "datasets"
collector:
    filename: "neutros"
    query: "(from:gabeiracombr OR from:renataloprete OR from:BishopWack) -is:retweet"
    max_results: 10000
    start_time: null
    end_time: null
    recent: true
database:
    host: ""
    database: ""
    user: ""
    password: ""
    tables:
        tweets: true
        users: true
        media: false
        places: false
